export const pricingCards = [
  {
    title: "Starter",
    description: "Perfect for trying out Plura",
    price: "Free",
    duration: "",
    highlight: "Keyy features",
    features: ["3 Sub accounts", "2 Team members", "Unlimited pipelines"],
    priceId: "",
  },
  {
    title: "Unlimited Saas",
    description: "The unlimited agency kit",
    price: "₹199",
    duration: "month",
    highlight: "Keyy features",
    features: ["Rebilling", "24/7 Support team"],
    priceId: "price_103rncorync21fdjwegru",
  },
  {
    title: "Basic",
    description: "For serious agency owners",
    price: "₹49",
    duration: "",
    highlight: "Keyy features",
    features: [
      "Unlimited Sub accounts",
      "Unlimited Team members",
      "Unlimited pipelines",
    ],
    priceId: "price_jcfni3y483bc3bcrir38n",
  },
];

import {
  BarChart,
  Headphones,
  Send,
  PipetteIcon,
  Calendar,
  Clipboard,
  Settings,
  User,
  PersonStandingIcon,
  SpeakerIcon,
  SectionIcon,
  Star,
  FileWarningIcon,
  Wallet,
  VideoIcon,
  File,
  Info,
  MessageCircleCodeIcon,
  BellRingIcon,
  Search,
  Power,
  Receipt,
  Shield,
  DollarSignIcon,
  Compass,
  Flag,
  LinkIcon,
  Home,
  Database,
  CheckIcon,
  CheckCircle,
  Tag,
  FileText,
  RocketIcon,
} from "lucide-react";

export const Icons = [
  {
    value: "chart",
    label: "Bar Chart",
    path: BarChart,
  },
  {
    value: "headphone",
    label: "Headphones",
    path: Headphones,
  },
  {
    value: "send",
    label: "Send",
    path: Send,
  },
  {
    value: "pipleines",
    label: "Pipelines",
    path: PipetteIcon,
  },
  {
    value: "calendar",
    label: "Calendar",
    path: Calendar,
  },
  {
    value: "clipboard",
    label: "Clipboard",
    path: Clipboard,
  },
  {
    value: "settings",
    label: "Settings",
    path: Settings,
  },
  {
    value: "user",
    label: "User",
    path: User,
  },
  {
    value: "person",
    label: "Person",
    path: PersonStandingIcon,
  },
  {
    value: "tune",
    label: "Tune",
    path: SpeakerIcon,
  },
  {
    value: "category",
    label: "Category",
    path: SectionIcon,
  },
  {
    value: "star",
    label: "Star",
    path: Star,
  },
  {
    value: "warning",
    label: "Warning",
    path: FileWarningIcon,
  },
  {
    value: "wallet",
    label: "Wallet",
    path: Wallet,
  },
  {
    value: "videorecorder",
    label: "Video Recorder",
    path: VideoIcon,
  },
  {
    value: "file",
    label: "File",
    path: File,
  },
  {
    value: "info",
    label: "Info",
    path: Info,
  },
  {
    value: "message",
    label: "Message",
    path: MessageCircleCodeIcon,
  },
  {
    value: "notification",
    label: "Notification",
    path: BellRingIcon,
  },
  {
    value: "search",
    label: "Search",
    path: Search,
  },
  {
    value: "power",
    label: "Power",
    path: Power,
  },
  {
    value: "receipt",
    label: "Receipt",
    path: Receipt,
  },
  {
    value: "shield",
    label: "Shield",
    path: Shield,
  },
  {
    value: "payment",
    label: "Payment",
    path: DollarSignIcon,
  },
  {
    value: "compass",
    label: "Compass",
    path: Compass,
  },
  {
    value: "flag",
    label: "Flag",
    path: Flag,
  },
  {
    value: "link",
    label: "Link",
    path: LinkIcon,
  },
  {
    value: "home",
    label: "Home",
    path: Home,
  },
  {
    value: "database",
    label: "Database",
    path: Database,
  },
  {
    value: "chip",
    label: "Chip",
    path: CheckIcon,
  },
  {
    value: "check",
    label: "Check Circled",
    path: CheckCircle,
  },
  {
    value: "tag",
    label: "Tag",
    path: Tag,
  },
  {
    value: "file-text",
    label: "File Text",
    path: FileText,
  },
  {
    Value: "clipboardIcon",
    label: "Launchpad",
    path: RocketIcon,
  },
];
